//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCW_Opener.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCW_Opener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   VRCW Opener に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File associations have been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileAssociation {
            get {
                return ResourceManager.GetString("FileAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File disassociations have been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDisassociation {
            get {
                return ResourceManager.GetString("FileDisassociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRChat World Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileTypeName {
            get {
                return ResourceManager.GetString("FileTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the {0} is incorrect.
        ///Would you like to reselect the file path? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectExeFilePath {
            get {
                return ResourceManager.GetString("IncorrectExeFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; is not the correct command line option. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectOptions {
            get {
                return ResourceManager.GetString("IncorrectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open (VR Mode)(&amp;O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenVRModeCommandName {
            get {
                return ResourceManager.GetString("OpenVRModeCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectExeFileDialogTitle {
            get {
                return ResourceManager.GetString("SelectExeFileDialogTitle", resourceCulture);
            }
        }
    }
}
